server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/WajahatSiddiqui/Configurations.git
          baseDir: target/config
          searchPaths: stock-handler
        native:
          searchLocations: file:../config-local